CREATE DATABASE simple_atm_software; 
USE simple_atm_software;
CREATE TABLE Users(AccNumber INT PRIMARY KEY AUTO_INCREMENT, FullName VARCHAR(255), CardNumber VARCHAR(255) UNIQUE, Pin VARCHAR(255));
ALTER TABLE Users AUTO_INCREMENT = 100001;
CREATE TABLE Accounts(CardNumber VARCHAR(255) PRIMARY KEY, FOREIGN KEY(CardNumber) REFERENCES Users(CardNumber), Transactions INT DEFAULT 0, Withdrawals INT DEFAULT 0, Amount DECIMAL(12,2) DEFAULT 0);
SET GLOBAL event_scheduler = ON;
CREATE EVENT ResetTransactionsEvent ON SCHEDULE EVERY 1 DAY STARTS TIMESTAMP(CURRENT_DATE) + INTERVAL 1 DAY DO UPDATE Accounts SET Withdrawals = 0;
CREATE TABLE Transactions(CardNumber VARCHAR(255), TransType VARCHAR(255), Amount DECIMAL(12,2), TransTime DATETIME)